default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: 5

development:
  <<: *default
  database: basic_development


test:
  <<: *default
  database: basic_test